/* File: "simple.c". Automatically generated by SBV. Do not edit! */

#include "simple.h"

SWord32 simple(const SWord32 x0, const SWord32 x1)
{
  const SWord32 s0 = x0;
  const SWord32 s1 = x1;
  const SWord32 s2 = s0 + s1;
  const SWord32 s4 = s2 * 0x00000005UL;
  const SWord32 s6 = s4 * 0x00000006UL;
  const SWord32 s8 = s6 >> 2;

  return s8;
}
